### ISSUE TITLE
Timeline for returning an item

### ISSUE THREAD

**Issue by bansalakhil** [vinsol-spree-contrib/spree_item_returns#13]
@nishant-cyro @priyank-gupta I think this extension is incomplete unless we have associated time to return the product. Can we have the time in days associated with the product, so that customer can request return until then. Currently customer has no time limit on returning a product.

**Comment by nishant-cyro** [comment]
@bansalakhil - Thanks for the suggestion, we will include it in our next version.

**Comment by PareshGupta** [comment]
@nishant-cyro - Done in PR #22
