### ISSUE TITLE
Return vs Exchange

### ISSUE THREAD

**Issue by bansalakhil** [vinsol-spree-contrib/spree_item_returns#16]
@nishant-cyro @priyank-gupta When customer is requesting for refund / exchange we should have a clear option for customer to choose from exchange vs refund. Right now if customer don't choose any option from the exchange for dropdown we take it as refund request. We can have a radio button exchange vs refund and show the exchange for dropdown only when exchange is chosen.

Also, Total pre-tax refund amount is displayed even if I have selected for exchange.

**Comment by nishant-cyro** [comment]
@bansalakhil - Thanks for the suggestions, we will look into it ASAP.

**Comment by PareshGupta** [comment]
@nishant-cyro - Done in PR #19
