### ISSUE TITLE
Return history page

### ISSUE THREAD

**Issue by bansalakhil** [vinsol-spree-contrib/spree_item_returns#17]
@nishant-cyro @priyank-gupta Return history page don't have any heading or way to go back

**Comment by nishant-cyro** [comment]
@bansalakhil - Thanks for pointing the issue, we will look into it and let you know when fixed.

**Comment by Anuragjain89** [comment]
@nishant-cyro Addressed this one in below PR.

https://github.com/vinsol-spree-contrib/spree_item_returns/pull/18
