### ISSUE TITLE
Issue with RETURNABLE checkbox of products in admin interface

### ISSUE THREAD

**Issue by mohansiriga7** [vinsol-spree-contrib/spree_item_returns#30]
Hi Vinsol team,

I have installed this extension and everything is working fine for me except the "Returnable" checkbox is only coming for products which doesn't have variants in admin interface. In spree_item_returns/app/overrides/spree/return_authorization/product_returnable_checkbox_button.rb, the deface code is displaying "Returnable" checkbox after Promotionable checkbox. But in spree_backend/app/views/spree/admin/products/_form.html.erb, the Promotionable checkbox only appears when the product has no variants. Since Promotionable checkbox doesn't show up for products with variants which in turn our Returnable checkbox is also not showing up. Is this intentional to display Returnable checkbox only for products which doesn't have variants, if so, how can customer exchanges for another variant of the same product. Or shall i modify the deface to show "Returnable" checkbox regardless of variants? Please let me know if i am missing anything here. By the way, thanks for this awesome gem.

**Comment by nimish13** [comment]
Hi @mohansiriga7 
Thanks for using this extension.
There was an issue in spree where Promotionable checkbox doesn't show up for the products those have variants but now it's been fixed in latest version of spree (3.3) and even backported to 3-1-stable.

If you are using 3-1-stable, I would recommend you to pull the latest code and if you are using 3-2-stable you can make use of this [PR](https://github.com/spree/spree/pull/8126/files ) to get the changes.
Once you have promotional product checkbox in product form the returnable checkbox will automatically get available in the product form.

**Comment by mohansiriga7** [comment]
Thanks for the quick response @nimish13 . Currently i am using spree 3.1.5 version and in spree_backend v 3.1.5 gem, the code is not showing Promotionable checkbox if the product has variants. 
![selection_024](https://user-images.githubusercontent.com/25999875/28458853-d300494a-6e28-11e7-8892-1ab4ea80e5de.png)

But, in github 3-1-stable branch, the code is showing promotionable checkbox regardless of variants
https://github.com/spree/spree/blob/3-1-stable/backend/app/views/spree/admin/products/_form.html.erb.
 I tried bundle update but still i am unable to get the code of 3-1-stable branch. Can you please tell me how can i get the latest code from 3-1-stable branch?

**Comment by nimish13** [comment]
@mohansiriga7 Alternatively you can have the changes in your app by creating `app/views/spree/admin/products/_form.html.erb.` and adding this [change](https://github.com/spree/spree/pull/8126/files).

**Comment by nimish13** [comment]
@mohansiriga7 Please let me know if we are good to close this issue.

**Comment by mohansiriga7** [comment]
@nimish13 Is there any other better way i can get the latest code without creating  app/views/spree/admin/products/_form.html.erb file in my skeleton project? I mean specifying spree_backend gem 3-1-stable branch in my gemfile like that. Thanks

**Comment by nimish13** [comment]
@mohansiriga7  please share your Gemfile

**Comment by mohansiriga7** [comment]
![selection_027](https://user-images.githubusercontent.com/25999875/28460519-0329c0fe-6e30-11e7-9905-ec7f4ca6139a.png)

![selection_025](https://user-images.githubusercontent.com/25999875/28460427-a4e22860-6e2f-11e7-8095-df2ee64b54aa.png)

![selection_026](https://user-images.githubusercontent.com/25999875/28460454-c8546bb4-6e2f-11e7-83ad-8e2e09a90312.png)

**Comment by tanmay3011** [comment]
Hi @mohansiriga7 

Sorry for the late reply. The change which you see in Github is marked against version [Spree 3.1.6](https://github.com/spree/spree/blob/v3.1.6/backend/app/views/spree/admin/products/_form.html.erb) not against [Spree 3.1.5](https://github.com/spree/spree/blob/v3.1.5/backend/app/views/spree/admin/products/_form.html.erb) 

So there are two ways of fixing this:
1. Overriding the view in the code base.
2. Updating Spree to 3.1.6 in case you don't have any issue updating it feel free to use the below-given command.
```bundle update spree```

Hope this resolves your issue.

**Comment by mohansiriga7** [comment]
Thanks for the replay @tanmay3011 ...I updated spree from 3.1.5 to 3.3.0 and everything is working fine for me now.
