### ISSUE TITLE
Returns History and Return Products buttons are not working in spree3.3

### ISSUE THREAD

**Issue by mohansiriga7** [vinsol-spree-contrib/spree_item_returns#31]
Hi Vinsol team,

I tried to install this extension for latest spree3.3 version, by modifying the dependency in gemspec file to s.add_dependency 'spree_core', '>= 3.1.5'
All seems to be good, however in a user flow of clicking on “Return Products” or when the user clicks on “Returns History” it throws an exception as attached as an image with this issue.

![selection_008](https://user-images.githubusercontent.com/25999875/30174978-8b3ae9f4-941a-11e7-81d7-b1c848037ad4.png)

Thanks and Regards,
Mohan Siriga

**Comment by tanmay3011** [comment]
Hi @mohansiriga7, Thanks for reporting this, I have fixed this issue in the master branch. As well as provided support for Spree 3.3.
