### ISSUE TITLE
How to install this on spree 4.1?

### ISSUE THREAD

**Issue by ankit-ziggle** [vinsol-spree-contrib/spree_item_returns#44]
I am trying to install it on spree 4.1 and after bundle install it shows me this

Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 4.1.6)

  In Gemfile:
    spree (~> 4.1) was resolved to 4.1.6, which depends on
      spree_core (= 4.1.6)

    spree_item_returns was resolved to 3.3.0, which depends on
      spree_core (>= 3.2.0, < 4.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
I tried bundle update but it does not work and running

bundle exec rails g spree_item_returns:install
it shows the following  message
The git source https://github.com/vinsol-spree-contrib/spree_item_returns.git is not yet checked out. Please run `bundle install` before trying to start your application

**Comment by TheodoreCha** [comment]
Hi!

How did you make that work?
